# Generated by Django 6.0.6 on 2026-08-25 01:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labreport_validation_status_labtest_is_group_test_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtestresult',
            options={'ordering': ['sort_order_snapshot']},
        ),
        migrations.AddField(
            model_name='labreport',
            name='barcode_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labreport',
            name='processed_at_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='labreport',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='visit_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='department_label',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='labtest',
            name='interpretation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='labtest',
            name='method',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='labtest',
            name='sample_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='flag',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('H', 'High'), ('L', 'Low')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='method_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='reference_range_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='section_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='sort_order_snapshot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='unit_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='labtestresult',
            name='result_value',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('reference_range', models.CharField(blank=True, default='', max_length=200)),
                ('ref_low', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ref_high', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=200)),
                ('section_title', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('result_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text'), ('qualitative', 'Qualitative')], default='numeric', max_length=20)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab.labtest')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='lab.labtestparameter'),
        ),
    ]
