# Generated by Django 6.0.6 on 2026-08-25 10:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_lab_templates_v3'),
        ('shared', '0002_add_pharmacy_branch_fields_to_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_name', models.CharField(blank=True, default='Clinical Laboratory', max_length=200)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.CharField(blank=True, default='', max_length=120)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('gstin', models.CharField(blank=True, default='', max_length=40)),
                ('nabl_reg_no', models.CharField(blank=True, default='', max_length=80)),
                ('processed_at_label', models.CharField(blank=True, default='', max_length=200)),
                ('pathologist_name', models.CharField(blank=True, default='', max_length=120)),
                ('pathologist_qualification', models.CharField(blank=True, default='', max_length=120)),
                ('pathologist_reg_no', models.CharField(blank=True, default='', max_length=80)),
                ('footer_note', models.CharField(blank=True, default='', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lab/logos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='lab/signatures/')),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_settings', to='shared.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
