# Generated by Django 6.0.6 on 2026-08-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_lab_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='visit_id_next_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='visit_id_padding',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='visit_id_prefix',
            field=models.CharField(blank=True, default='LABV', max_length=20),
        ),
    ]
