# Generated by Django 5.0.7 on 2026-06-30 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0009_ipddailyprocesslog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ipddailyprocesslog',
            new_name='ipd_ipddail_admissi_ff86b4_idx',
            old_name='ipd_process_adm_date_idx',
        ),
        migrations.RenameIndex(
            model_name='ipddailyprocesslog',
            new_name='ipd_ipddail_hospita_6a326d_idx',
            old_name='ipd_process_hosp_date_idx',
        ),
        migrations.AlterField(
            model_name='ipddailyprocesslog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='ipddailyprocesslog',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
