# Generated by Django 5.0.7 on 2026-09-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0012_ipddailyprocesslog_template_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='admission_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
