# Generated by Django 5.0.7 on 2026-07-04 08:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_voided_field'),
        ('ipd', '0012_ipddailyprocesslog_template_snapshot'),
        ('patients', '0005_patient_opd_custom_fields'),
        ('shared', '0002_add_pharmacy_branch_fields_to_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDFinalBill',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_no', models.CharField(blank=True, max_length=60)),
                ('patient_name', models.CharField(blank=True, max_length=300)),
                ('guardian_name', models.CharField(blank=True, max_length=300)),
                ('patient_phone', models.CharField(blank=True, max_length=30)),
                ('patient_address', models.TextField(blank=True)),
                ('consultant_name', models.CharField(blank=True, max_length=200)),
                ('room_bed', models.CharField(blank=True, max_length=100)),
                ('scheme_name', models.CharField(blank=True, max_length=200)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_bill', to='ipd.ipdadmission')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_final_bills', to='shared.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipd_final_bills', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='IPDFinalBillItem',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.ipdfinalbill')),
            ],
        ),
        migrations.AddIndex(
            model_name='ipdfinalbill',
            index=models.Index(fields=['hospital', 'bill_no'], name='billing_ipd_hospita_eeca61_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdfinalbill',
            index=models.Index(fields=['patient', 'created_at'], name='billing_ipd_patient_a451b7_idx'),
        ),
        migrations.AddIndex(
            model_name='ipdfinalbillitem',
            index=models.Index(fields=['final_bill', 'description'], name='billing_ipd_final_b_afa1a0_idx'),
        ),
    ]
