# Generated by Django 5.0.7 on 2026-07-04 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_ipdfinalbill_ipdfinalbillitem_and_more'),
        ('shared', '0002_add_pharmacy_branch_fields_to_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDFinalBillSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.PositiveIntegerField()),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipd_final_bill_sequences', to='shared.hospital')),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', 'year'], name='billing_ipd_hospita_f3246d_idx')],
                'unique_together': {('hospital', 'year')},
            },
        ),
    ]
