# Generated by Django 6.0.6 on 2026-09-05 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_ipdfinalbillsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdfinalbill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
