# Generated by Django 6.0.6 on 2026-09-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_ipdfinalbill_created_at_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDAdvanceInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'IPD Advance Bill',
                'verbose_name_plural': 'IPD Advance Bills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billinginvoice',),
        ),
        migrations.CreateModel(
            name='IPDRefundInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'IPD Refund Bill',
                'verbose_name_plural': 'IPD Refund Bills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billinginvoice',),
        ),
        migrations.CreateModel(
            name='IPDRoomInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'IPD Room Bill',
                'verbose_name_plural': 'IPD Room Bills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billinginvoice',),
        ),
        migrations.CreateModel(
            name='IPDServiceInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'IPD Service Bill',
                'verbose_name_plural': 'IPD Service Bills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billinginvoice',),
        ),
        migrations.CreateModel(
            name='OPDBillingInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'OPD Bill',
                'verbose_name_plural': 'OPD Bills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billinginvoice',),
        ),
        migrations.CreateModel(
            name='OtherBillingInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Other Bill',
                'verbose_name_plural': 'Other Bills',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billing.billinginvoice',),
        ),
    ]
