# Generated by Django 6.0.6 on 2026-08-02 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0012_voided_field'),
        ('shared', '0002_add_pharmacy_branch_fields_to_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='opdvisit',
            name='opd_payment_slip_no',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='OPDPaymentSlipSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.PositiveIntegerField()),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opd_payment_slip_sequences', to='shared.hospital')),
            ],
            options={
                'unique_together': {('hospital', 'year')},
            },
        ),
    ]
