# Generated by Django 6.0.4 on 2026-04-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.hospital'),
        ),
    ]
