# Generated by Django 6.0.4 on 2026-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_candidate_options_remove_candidate_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
