# Generated by Django 6.0.4 on 2026-04-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_candidate_cover_letter_candidate_current_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
