# Generated by Django 6.0.4 on 2026-04-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_candidate_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
