# Generated by Django 6.0.4 on 2026-04-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_candidate_serial_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('job_opening', 'email'), name='unique_job_application_by_email'),
        ),
    ]
