# Generated by Django 6.0.4 on 2026-04-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_candidate_unique_job_application_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
