# Generated by Django 6.0.4 on 2026-04-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_candidate_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('on_hold', 'On Hold'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
