# Generated by Django 6.0.4 on 2026-04-28 14:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_add_recruitment_pipeline_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferTemplate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard Offer Letter')", max_length=200)),
                ('content', models.TextField(help_text='Template content with placeholders: {candidate_name}, {job_title}, {company_name}, etc.')),
                ('company_name', models.CharField(help_text='Company name', max_length=200)),
                ('company_address', models.TextField(help_text='Full company address')),
                ('company_email', models.EmailField(help_text='Company email address', max_length=254)),
                ('company_phone', models.CharField(help_text='Company phone number', max_length=20)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='company_logos/')),
                ('hr_name', models.CharField(help_text='HR manager name for signature', max_length=200)),
                ('hr_designation', models.CharField(help_text='HR manager designation', max_length=200)),
                ('hr_signature', models.ImageField(blank=True, help_text='HR signature image', null=True, upload_to='hr_signatures/')),
                ('job_title', models.CharField(help_text='Default job title', max_length=200)),
                ('department', models.CharField(help_text='Default department', max_length=200)),
                ('job_location', models.CharField(help_text='Default job location', max_length=200)),
                ('employment_type', models.CharField(help_text='Default employment type (e.g., Full-time, Part-time)', max_length=50)),
                ('default_ctc', models.DecimalField(blank=True, decimal_places=2, help_text='Default CTC (Cost to Company)', max_digits=12, null=True)),
                ('default_basic_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Default basic salary', max_digits=12, null=True)),
                ('default_hra', models.DecimalField(blank=True, decimal_places=2, help_text='Default HRA (House Rent Allowance)', max_digits=12, null=True)),
                ('default_allowances', models.DecimalField(blank=True, decimal_places=2, help_text='Default allowances', max_digits=12, null=True)),
                ('default_bonus', models.DecimalField(blank=True, decimal_places=2, help_text='Default bonus', max_digits=12, null=True)),
                ('default_work_shift', models.CharField(blank=True, help_text="Default work shift (e.g., 'Morning 9 AM - 6 PM')", max_length=100, null=True)),
                ('default_working_hours', models.CharField(blank=True, help_text="Default working hours per day (e.g., '8 hours')", max_length=50, null=True)),
                ('default_weekly_off', models.CharField(default='Saturday, Sunday', help_text='Default weekly off days', max_length=50)),
                ('default_probation_period', models.CharField(default='6 months', help_text='Default probation period', max_length=100)),
                ('default_notice_period', models.CharField(default='30 days', help_text='Default notice period', max_length=100)),
                ('terms_conditions', models.TextField(default='This offer is subject to satisfactory completion of background verification and submission of required documents.', help_text='Terms and conditions for the offer')),
            ],
            options={
                'verbose_name': 'Offer Template',
                'verbose_name_plural': 'Offer Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
