# Generated by Django 6.0.4 on 2026-04-29 08:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_offertemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_address', models.TextField(blank=True, default='')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='offer_company_logos/')),
                ('hr_name', models.CharField(max_length=200)),
                ('hr_designation', models.CharField(max_length=200)),
                ('hr_signature', models.ImageField(blank=True, null=True, upload_to='offer_hr_signatures/')),
                ('job_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=50)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('allowances', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('joining_date', models.DateField()),
                ('work_shift', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('weekly_off', models.CharField(default='Saturday, Sunday', max_length=50)),
                ('probation_period', models.CharField(default='6 months', max_length=100)),
                ('notice_period', models.CharField(default='30 days', max_length=100)),
                ('terms_conditions', models.TextField()),
                ('offer_expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='hr.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='hr.jobopening')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='hr.offertemplate')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['created', 'sent', 'accepted'])), fields=('candidate',), name='unique_active_offer_per_candidate')],
            },
        ),
    ]
