# Generated by Django 6.0.4 on 2026-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
