# Generated by Django 6.0.4 on 2026-05-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_offer_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='offer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
