# Generated by Django 6.0.4 on 2026-05-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_alter_candidate_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='responsibilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='responsibilities',
            field=models.TextField(blank=True, default='', help_text='Default job responsibilities (bullet points)'),
        ),
    ]
