# Generated by Django 6.0.4 on 2026-05-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_offer_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='edited_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='edited_layout_config',
            field=models.JSONField(blank=True, default=dict, help_text='Per-offer layout overrides from editor', null=True),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, help_text='Optional editor layout metadata (logo position, typography defaults)', null=True),
        ),
        migrations.AlterField(
            model_name='offertemplate',
            name='responsibilities',
            field=models.TextField(blank=True, default='<ul>\n    <li><strong>Product Development:</strong>\n        <ul>\n            <li>Assist in the design, development, and testing of new products or enhancements.</li>\n            <li>Contribute innovative ideas to improve product features and functionalities.</li>\n        </ul>\n    </li>\n    <li><strong>Documentation:</strong>\n        <ul>\n            <li>Maintain accurate and up-to-date documentation for all engineering processes and project work.</li>\n            <li>Create and update technical documentation, including manuals and specifications.</li>\n        </ul>\n    </li>\n    <li><strong>Quality Assurance:</strong>\n        <ul>\n            <li>Participate in quality assurance processes to ensure that products meet established standards and customer requirements.</li>\n            <li>Conduct thorough testing and analysis to identify and resolve potential issues.</li>\n        </ul>\n    </li>\n    <li><strong>Continuous Learning:</strong>\n        <ul>\n            <li>Stay updated on industry trends, technologies, and best practices.</li>\n            <li>Participate in ongoing professional development activities to enhance skills and knowledge.</li>\n        </ul>\n    </li>\n    <li><strong>Collaborative Problem Solving:</strong>\n        <ul>\n            <li>Work closely with team members to identify and address technical challenges.</li>\n            <li>Contribute to brainstorming sessions and offer solutions for complex engineering problems.</li>\n        </ul>\n    </li>\n</ul>', help_text='Default job responsibilities (bullet points)'),
        ),
    ]
