# Generated by Django 6.0.4 on 2026-05-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_componentoffertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='component_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.componentoffertemplate'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='hr.offertemplate'),
        ),
    ]
