# Generated by Django 6.0.4 on 2026-05-03 17:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_offer_component_template_alter_offer_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBuilderData',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(max_length=20)),
                ('candidate_address', models.TextField()),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('reporting_manager', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('work_mode', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('basic_salary', models.CharField(max_length=50)),
                ('hra', models.CharField(max_length=50)),
                ('special_allowance', models.CharField(max_length=50)),
                ('bonus', models.CharField(max_length=50)),
                ('ctc', models.CharField(max_length=50)),
                ('working_hours', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('weekly_off', models.CharField(max_length=100)),
                ('probation_period', models.CharField(max_length=100)),
                ('notice_period', models.CharField(max_length=100)),
                ('hr_name', models.CharField(max_length=255)),
                ('hr_designation', models.CharField(max_length=255)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.candidate')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.offertemplate')),
            ],
            options={
                'verbose_name': 'Offer Builder Data',
                'verbose_name_plural': 'Offer Builder Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
