# Generated by Django 6.0.4 on 2026-05-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_offerbuilderv2_delete_offerbuilderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbuilderv2',
            name='blocks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='global_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
