# Generated by Django 6.0.4 on 2026-05-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_offerbuilderv2_blocks_offerbuilderv2_global_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerbuilderv2',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='offerbuilderv2',
            name='global_config',
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='candidate_name_salutation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='candidate_sig_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='company_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='company_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='company_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='date_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='date_line_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='date_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='dear_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='dynamic_content',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='letter_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='ref_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='ref_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='signatory_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='subject_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='subject_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='to_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='basic_salary',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='bonus',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='candidate_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='candidate_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='candidate_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='candidate_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='ctc',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='hr_designation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='hr_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='hra',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='job_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='notice_period',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='probation_period',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='reporting_manager',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='shift',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='special_allowance',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='weekly_off',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='work_mode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
