# Generated by Django 6.0.4 on 2026-05-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_remove_offerbuilderv2_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbuilderv2',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
