# Generated by Django 6.0.4 on 2026-05-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_offerbuilderv2_is_sent_offerbuilderv2_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbuilderv2',
            name='candidate_name_font_size',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='company_name_font_size',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='letter_title_font_size',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='offerbuilderv2',
            name='font_size',
            field=models.IntegerField(default=14),
        ),
    ]
