# Generated by Django 6.0.4 on 2026-05-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_employee_table_synced'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual salary', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
