# Generated by Django 6.0.4 on 2026-05-06 11:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_alter_employee_unique_together_employee_job_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_status',
            field=models.CharField(choices=[('pending_documents', 'Pending Documents'), ('documents_uploaded', 'Documents Uploaded'), ('under_review', 'Under Review'), ('ready_to_join', 'Ready to Join'), ('joined', 'Joined'), ('not_joined', 'Not Joined')], db_index=True, default='pending_documents', help_text='Track employee onboarding progress', max_length=30),
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('degree', 'Degree Certificate'), ('bank', 'Bank Account Details'), ('address_proof', 'Address Proof'), ('experience_letter', 'Experience Letter'), ('salary_slip', 'Previous Salary Slip'), ('photo', 'Passport Size Photo'), ('other', 'Other Document')], max_length=20)),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'document_type'), name='unique_employee_document_type')],
            },
        ),
    ]
