# Generated by Django 6.0.4 on 2026-05-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_employee_onboarding_status_employeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joining_date_confirmed',
            field=models.DateField(blank=True, help_text='Actual date employee joined', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('not_joined', 'Not Joined'), ('ready_to_join', 'Ready to Join'), ('joined', 'Joined'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='not_joined', max_length=20),
        ),
    ]
