# Generated by Django 6.0.4 on 2026-05-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_employee_joining_date_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='welcome_email_sent',
            field=models.BooleanField(default=False, help_text='Whether welcome email with onboarding link has been sent'),
        ),
        migrations.AddField(
            model_name='employee',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when welcome email was sent', null=True),
        ),
    ]
