# Generated by Django 6.0.4 on 2026-05-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_employee_welcome_email_sent_and_more'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='welcome_email_sent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='welcome_email_sent_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.hospital'),
        ),
    ]
