# Generated by Django 6.0.4 on 2026-05-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_remove_employee_welcome_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to='hr.candidate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to='hr.offer'),
        ),
    ]
