# Generated by Django 6.0.4 on 2026-05-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0032_employee_candidate_employee_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='onboarding_status',
            field=models.CharField(choices=[('pending_documents', 'Pending Documents'), ('partial_documents', 'Partial Documents'), ('documents_uploaded', 'Documents Uploaded'), ('under_review', 'Under Review'), ('ready_to_join', 'Ready to Join'), ('onboarded', 'Onboarded')], db_index=True, default='pending_documents', help_text='Track employee onboarding progress', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('pending_onboarding', 'Pending Onboarding'), ('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], db_index=True, default='pending_onboarding', max_length=30),
        ),
    ]
