# Generated by Django 5.0.7 on 2026-05-12 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_alter_employee_onboarding_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='onboarding_token_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(
                choices=[
                    ('aadhaar', 'Aadhaar Card'),
                    ('aadhar', 'Aadhar Card'),
                    ('pan', 'PAN Card'),
                    ('resume', 'Resume'),
                    ('degree', 'Degree Certificate'),
                    ('bank', 'Bank Details'),
                    ('address_proof', 'Address Proof'),
                    ('experience_letter', 'Experience Letter'),
                    ('salary_slip', 'Previous Salary Slip'),
                    ('photo', 'Passport Size Photo'),
                    ('other', 'Other Document'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending Review'),
                    ('uploaded', 'Uploaded'),
                    ('verified', 'Verified'),
                    ('rejected', 'Rejected'),
                    ('reupload_requested', 'Re-upload Requested'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='EmployeeDocumentAuditLog',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(
                    choices=[
                        ('approved', 'Approved'),
                        ('rejected', 'Rejected'),
                        ('reupload_requested', 'Re-upload Requested'),
                        ('employee_activated', 'Employee Activated'),
                    ],
                    max_length=30,
                )),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='audit_logs',
                    to='hr.employeedocument',
                )),
                ('employee', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='document_audit_logs',
                    to='hr.employee',
                )),
                ('performed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='employee_document_audit_logs',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
