# Generated by Django 6.0.4 on 2026-05-12 19:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0034_employee_onboarding_completed_and_document_review'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocumentauditlog',
            name='action',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reupload_requested', 'Re-upload Requested'), ('physically_verified', 'Physically Verified'), ('override_approved', 'Override Approved'), ('employee_activated', 'Employee Activated')], max_length=30),
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('mandatory', models.BooleanField(default=True)),
                ('verification_mode', models.CharField(choices=[('upload', 'Upload'), ('physical', 'Physical'), ('hybrid', 'Hybrid')], default='upload', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocumentRequirement',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('reupload_requested', 'Re-upload Requested'), ('physically_verified', 'Physically Verified')], default='pending', max_length=30)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='employee_requirements/%Y/%m/')),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('physically_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('override_approved', models.BooleanField(default=False)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_requirements', to='hr.documenttype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='hr.employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employeedocumentauditlog',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='hr.employeedocumentrequirement'),
        ),
        migrations.CreateModel(
            name='OnboardingChecklistRule',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, default='', max_length=120)),
                ('mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_rules', to='hr.documenttype')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='unique_document_type_per_hospital'),
        ),
        migrations.AddConstraint(
            model_name='employeedocumentrequirement',
            constraint=models.UniqueConstraint(fields=('employee', 'document_type'), name='unique_employee_document_requirement'),
        ),
        migrations.AddConstraint(
            model_name='onboardingchecklistrule',
            constraint=models.UniqueConstraint(fields=('hospital', 'department', 'role_name', 'document_type'), name='unique_checklist_rule_scope'),
        ),
    ]
