# Generated by Django 6.0.4 on 2026-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0035_alter_employeedocumentauditlog_action_documenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbuilderv2',
            name='company_block_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='company_meta_font_size',
            field=models.IntegerField(default=16),
        ),
    ]
