# Generated by Django 6.0.4 on 2026-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0036_offerbuilderv2_company_block_and_meta_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbuilderv2',
            name='company_website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offerbuilderv2',
            name='letter_section_fonts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
