# Generated by Django 6.0.4 on 2026-05-13 15:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0038_offer_onboarding_welcome_email_sent_at'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Timezone-aware punch timestamp.')),
                ('punch_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('source', models.CharField(choices=[('biometric', 'Biometric'), ('employee_portal', 'Employee Portal'), ('HR_manual', 'HR Manual'), ('import', 'Import')], default='import', max_length=30)),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('device_metadata', models.JSONField(blank=True, default=dict)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_check_in', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('first_check_in', models.DateTimeField(blank=True, null=True)),
                ('last_check_out', models.DateTimeField(blank=True, null=True)),
                ('total_work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('weekend', 'Weekend'), ('work_from_office', 'Work From Office')], db_index=True, default='absent', max_length=30)),
                ('calculation_locked', models.BooleanField(default=False)),
                ('manually_corrected', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date', 'employee_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='employeeshift',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Primary assigned shift. Future shift rotation can be tracked in EmployeeShift.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.shift'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shift',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='full_day_hours',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
        migrations.AddField(
            model_name='shift',
            name='grace_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='half_day_hours',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
        ),
        migrations.AddField(
            model_name='shift',
            name='overtime_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='hr.shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name='employeeshift',
            index=models.Index(fields=['employee', 'effective_from'], name='hr_employee_employe_5d8a88_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshift',
            index=models.Index(fields=['shift', 'effective_from'], name='hr_employee_shift_i_9adf5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('hospital', 'code'), name='unique_shift_code_per_hospital'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='unique_shift_name_per_hospital'),
        ),
        migrations.AddField(
            model_name='attendancepunch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_punches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancepunch',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_punches', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='attendancepunch',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_punches_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_regularizations', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_regularizations_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_attendance', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendance', to='hr.shift'),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularizations', to='hr.dailyattendance'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['employee', 'timestamp'], name='hr_attendan_employe_afed77_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['source', 'timestamp'], name='hr_attendan_source_037c30_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['is_void', 'timestamp'], name='hr_attendan_is_void_fd0c07_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancepunch',
            constraint=models.UniqueConstraint(fields=('employee', 'timestamp', 'punch_type', 'source', 'device_id'), name='unique_attendance_punch_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['date', 'attendance_status'], name='hr_dailyatt_date_8cfaf3_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['employee', 'date'], name='hr_dailyatt_employe_a1b6f6_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['calculation_locked'], name='hr_dailyatt_calcula_be312c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_daily_attendance_per_employee_date'),
        ),
        migrations.AddIndex(
            model_name='attendanceregularization',
            index=models.Index(fields=['employee', 'status'], name='hr_attendan_employe_55af56_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceregularization',
            index=models.Index(fields=['created_at'], name='hr_attendan_created_642ef6_idx'),
        ),
    ]
