# Generated by Django 6.0.4 on 2026-05-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0039_attendancepunch_attendanceregularization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_overnight',
            field=models.BooleanField(default=False),
        ),
    ]
