# Generated by Django 6.0.4 on 2026-05-13 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0040_shift_description_shift_is_overnight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepunch',
            name='attendance_date',
            field=models.DateField(blank=True, db_index=True, help_text='Working date bucket for future attendance engine; supports overnight shifts.', null=True),
        ),
        migrations.AddField(
            model_name='attendancepunch',
            name='correction_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attendancepunch',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_candidates', to='hr.attendancepunch'),
        ),
        migrations.AddField(
            model_name='attendancepunch',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancepunch',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Shift snapshot at punch creation time; supports future shift rotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_punches', to='hr.shift'),
        ),
        migrations.AddField(
            model_name='attendancepunch',
            name='suspicious_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['employee', 'attendance_date'], name='hr_attendan_employe_0ce7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['shift', 'attendance_date'], name='hr_attendan_shift_i_3be9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['is_suspicious', 'timestamp'], name='hr_attendan_is_susp_f61402_idx'),
        ),
    ]
