# Generated by Django 6.0.4 on 2026-05-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0041_attendancepunch_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancepunch',
            name='unique_attendance_punch_fingerprint',
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='calculation_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='incomplete_punches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='last_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='original_calculated_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='requires_hr_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['requires_hr_review'], name='hr_dailyatt_require_0f9bb8_idx'),
        ),
    ]
