# Generated by Django 6.0.4 on 2026-05-15 11:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0048_candidate_interview_meeting_link_venue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewBulkAuditLog',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('schedule', 'Schedule'), ('reschedule', 'Reschedule'), ('cancel', 'Cancel')], max_length=20)),
                ('candidate_ids', models.JSONField(default=list, help_text='UUID strings of candidates affected')),
                ('affected_count', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-scheduled_start']},
        ),
        migrations.AddField(
            model_name='interview',
            name='bulk_batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='interview',
            name='location_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interview',
            name='office_address',
            field=models.TextField(blank=True, default='', help_text='For in-person interviews'),
        ),
        migrations.AddField(
            model_name='interview',
            name='platform',
            field=models.CharField(blank=True, default='', help_text='e.g. Google Meet, Zoom', max_length=100),
        ),
        migrations.AddField(
            model_name='interview',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, help_text='Computed end; used for overlap checks.', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='scheduled_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='IANA timezone used when interpreting date/time for this interview.', max_length=64),
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hr.candidate'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='result',
            field=models.CharField(blank=True, default='', help_text='Legacy / short outcome note', max_length=100),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['candidate', 'status', 'scheduled_start'], name='hr_intervie_candida_45c502_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'scheduled_start'], name='hr_intervie_status_b89f47_idx'),
        ),
        migrations.AddField(
            model_name='interviewbulkauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_bulk_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
