# Generated by Django 6.0.4 on 2026-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0049_interview_enterprise_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='application_source',
            field=models.CharField(blank=True, default='', help_text='How the candidate applied (referral, job board, etc.)', max_length=120),
        ),
    ]
