# Generated by Django 6.0.4 on 2026-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0050_candidate_application_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentoffertemplate',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Optional grouping (e.g. Teaching, Engineering, Internship)', max_length=100),
        ),
    ]
