# Generated by Django 6.0.4 on 2026-05-16 11:45

import apps.shared.email_mixins
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def backfill_recruitment_ids(apps, schema_editor):
    Candidate = apps.get_model('hr', 'Candidate')
    CandidateProfile = apps.get_model('hr', 'CandidateProfile')
    RecruitmentIdSequence = apps.get_model('hr', 'RecruitmentIdSequence')

    cand_seq = 0
    app_seq = 0
    profile_cache = {}

    for row in Candidate.objects.select_related('job_opening').order_by('created_at'):
        hospital_id = None
        if row.job_opening_id:
            hospital_id = row.job_opening.hospital_id

        email_raw = (row.email or '').strip()
        email_key = email_raw.lower() if email_raw else ''

        cache_key = (hospital_id, email_key) if email_key else None
        profile = profile_cache.get(cache_key) if cache_key else None

        if profile is None:
            cand_seq += 1
            profile = CandidateProfile.objects.create(
                hospital_id=hospital_id,
                candidate_code=f'CAND-{cand_seq:06d}',
                name=row.name,
                email=email_raw,
                phone=row.phone or '',
            )
            if cache_key:
                profile_cache[cache_key] = profile
        elif Candidate.objects.filter(
            job_opening_id=row.job_opening_id,
            profile_id=profile.id,
        ).exclude(pk=row.pk).exists():
            cand_seq += 1
            profile = CandidateProfile.objects.create(
                hospital_id=hospital_id,
                candidate_code=f'CAND-{cand_seq:06d}',
                name=row.name,
                email=email_raw,
                phone=row.phone or '',
            )

        app_seq += 1
        row.profile_id = profile.id
        row.application_code = f'APP-{app_seq:06d}'
        row.save(update_fields=['profile_id', 'application_code'])

    RecruitmentIdSequence.objects.update_or_create(
        prefix='CAND',
        defaults={'last_seq': cand_seq},
    )
    RecruitmentIdSequence.objects.update_or_create(
        prefix='APP',
        defaults={'last_seq': app_seq},
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0053_offerlettersettings_contact_fields'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(apps.shared.email_mixins.NormalizeEmailFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RecruitmentIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prefix', models.CharField(max_length=8, unique=True)),
                ('last_seq', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='candidate',
            name='unique_job_application_by_email',
        ),
        migrations.AddField(
            model_name='candidate',
            name='application_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='serial_number',
            field=models.IntegerField(blank=True, help_text='Deprecated per-job counter; use application_code instead.', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profiles', to='shared.hospital'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='hr.candidateprofile'),
        ),
        migrations.RunPython(backfill_recruitment_ids, noop_reverse),
    ]
