# Generated by Django 6.0.4 on 2026-05-18 14:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0061_offer_letter_enterprise_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepunch',
            name='source',
            field=models.CharField(
                choices=[
                    ('biometric', 'Biometric'),
                    ('employee_portal', 'Employee Portal'),
                    ('HR_manual', 'HR Manual'),
                    ('MANUAL_BIOMETRIC_SIMULATION', 'Manual Biometric Simulation'),
                    ('import', 'Import'),
                    ('system', 'System'),
                ],
                default='import',
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='AttendanceControlAuditLog',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(db_index=True)),
                ('requested_status', models.CharField(max_length=20)),
                ('action', models.CharField(db_index=True, default='mark_attendance', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('punch_ids', models.JSONField(blank=True, default=list)),
                ('result_status', models.CharField(blank=True, default='', max_length=30)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                (
                    'daily_attendance',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='control_audit_logs',
                        to='hr.dailyattendance',
                    ),
                ),
                (
                    'employee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attendance_control_audit_logs',
                        to='hr.employee',
                    ),
                ),
                (
                    'marked_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='attendance_control_marks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancecontrolauditlog',
            index=models.Index(fields=['employee', 'attendance_date'], name='hr_attendan_employe_c908ea_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancecontrolauditlog',
            index=models.Index(fields=['marked_by', 'created_at'], name='hr_attendan_marked__f0ae9e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancecontrolauditlog',
            index=models.Index(fields=['action', 'created_at'], name='hr_attendan_action_3e7ad8_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancecontrolauditlog',
            constraint=models.UniqueConstraint(
                condition=models.Q(('action', 'mark_attendance'), ('success', True)),
                fields=('employee', 'attendance_date'),
                name='unique_successful_attendance_control_mark_per_day',
            ),
        ),
    ]
