# Generated by Django 6.0.4 on 2026-06-05 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0070_payroll_approval_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerbuilderv2',
            options={'ordering': ['-created_at'], 'verbose_name': 'Offer Builder', 'verbose_name_plural': 'Offer Builder'},
        ),
        migrations.RenameIndex(
            model_name='interviewreminder',
            new_name='hr_intervie_is_sent_4d8a35_idx',
            old_name='hr_intervie_is_sent_7f3a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollauditlog',
            new_name='hr_payrolla_payroll_04879f_idx',
            old_name='hr_payroll_run_action_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollauditlog',
            new_name='hr_payrolla_payroll_891a50_idx',
            old_name='hr_payroll_run_created_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentemailevent',
            new_name='hr_recruitm_candida_b4e014_idx',
            old_name='hr_recruitm_candida_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentemailevent',
            new_name='hr_recruitm_event_t_b808a6_idx',
            old_name='hr_recruitm_event_t_4c9e8a_idx',
        ),
        migrations.AlterField(
            model_name='applicationdocumentrequirement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='applicationdocumentrequirement',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='total_work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total worked hours (summary engine output).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatustransition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='documentstatustransition',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeedocumentuploadversion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='employeedocumentuploadversion',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interviewreminder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='interviewreminder',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobdocumentrequirement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='jobdocumentrequirement',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Deduction line items, e.g. {"lop": 2000, "pf": 1800, "late_penalty": 75}.'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='earnings_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Earnings line items, e.g. {"basic_salary": 30000, "hra": 12000, "overtime": 500}.'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated payslip PDF.', null=True, upload_to='payslips/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='recruitmentemailevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='recruitmentemailevent',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
