# Generated by Django 6.0.4 on 2026-06-06 14:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0071_alter_offerbuilderv2_options_and_more'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('assignment_type', models.CharField(choices=[('ALL', 'All Employees'), ('DEPARTMENT', 'Department'), ('EMPLOYEE', 'Specific Employee')], default='ALL', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicyLine',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_days', models.DecimalField(blank=True, decimal_places=2, help_text='Annual allocation. Leave blank for unlimited.', max_digits=6, null=True)),
                ('is_unlimited', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['leave_type__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='annual_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max days per year. Leave blank for unlimited.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='shared.hospital'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['hospital', 'is_active'], name='hr_leavetyp_hospita_ef0acb_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('hospital', 'code'), name='unique_leave_type_code_per_hospital'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_policies', to='hr.department'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='shared.hospital'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balances', to='hr.leavepolicy'),
        ),
        migrations.AddField(
            model_name='leavepolicyline',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_lines', to='hr.leavetype'),
        ),
        migrations.AddField(
            model_name='leavepolicyline',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hr.leavepolicy'),
        ),
        migrations.AddIndex(
            model_name='leavepolicy',
            index=models.Index(fields=['hospital', 'assignment_type', 'is_active'], name='hr_leavepol_hospita_6126ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='leavepolicyline',
            constraint=models.UniqueConstraint(fields=('policy', 'leave_type'), name='unique_policy_leave_type'),
        ),
    ]
