# Generated by Django 6.0.4 on 2026-06-08 09:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0072_leave_management_enterprise'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePortalNotification',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_submitted', 'Leave Submitted'), ('regularization_approved', 'Miss Punch Approved'), ('regularization_rejected', 'Miss Punch Rejected'), ('regularization_submitted', 'Miss Punch Submitted'), ('document_approved', 'Document Approved'), ('document_reupload', 'Document Reupload Requested'), ('offer_accepted', 'Offer Accepted'), ('portal_activation', 'Portal Activation'), ('payroll', 'Payroll'), ('general', 'General')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_notifications', to='hr.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'read_at'], name='hr_employee_employe_50f799_idx'), models.Index(fields=['employee', 'created_at'], name='hr_employee_employe_66a8bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationHoliday',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('national', 'National'), ('organization', 'Organization'), ('hospital', 'Hospital')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_holidays', to='shared.hospital')),
            ],
            options={
                'ordering': ['date', 'name'],
                'indexes': [models.Index(fields=['scope', 'date'], name='hr_organiza_scope_982f84_idx'), models.Index(fields=['hospital', 'date'], name='hr_organiza_hospita_5b0195_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'hospital', 'date', 'name'), name='hr_org_holiday_unique_scope_date_name')],
            },
        ),
    ]
