# Generated by Django 6.0.4 on 2026-06-08

from django.db import migrations, models


def migrate_hospital_to_organization(apps, schema_editor):
    OrganizationHoliday = apps.get_model('hr', 'OrganizationHoliday')
    OrganizationHoliday.objects.filter(scope='hospital').update(scope='organization')


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0073_employee_portal_notifications_holidays'),
    ]

    operations = [
        migrations.RunPython(migrate_hospital_to_organization, migrations.RunPython.noop),
        migrations.AddField(
            model_name='organizationholiday',
            name='is_paid_day',
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text='Reserved for payroll: whether this holiday counts as a paid working day.',
            ),
        ),
        migrations.AlterField(
            model_name='organizationholiday',
            name='scope',
            field=models.CharField(
                choices=[
                    ('national', 'National Holiday'),
                    ('festival', 'Festival Holiday'),
                    ('organization', 'Organization Holiday'),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
