# Generated by Django 6.0.4 on 2026-06-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0074_organization_holiday_festival_paid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='onboardingchecklistrule',
            name='unique_checklist_rule_scope',
        ),
        migrations.DeleteModel(
            name='OnboardingChecklistRule',
        ),
    ]
