# Generated by Django 6.0.4 on 2026-06-09 09:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0075_remove_onboarding_checklist_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_ref',
            field=models.ForeignKey(blank=True, help_text='Canonical department link for payroll and policy assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.department'),
        ),
        migrations.CreateModel(
            name='DepartmentSalaryStructure',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('allowances', models.JSONField(blank=True, default=dict, help_text='Flexible allowance breakdown, e.g. {"transport": 1500, "medical": 800}.')),
                ('deductions', models.JSONField(blank=True, default=dict, help_text='Fixed monthly deductions, e.g. {"pf": 1800, "professional_tax": 200}.')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hourly overtime rate applied when shift policy allows OT.', max_digits=10)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_structures', to='hr.department')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='source_department_structure',
            field=models.ForeignKey(blank=True, help_text='Department template this assignment was copied from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_assignments', to='hr.departmentsalarystructure'),
        ),
        migrations.AddIndex(
            model_name='departmentsalarystructure',
            index=models.Index(fields=['department', 'effective_from'], name='hr_departme_departm_1be89d_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentsalarystructure',
            index=models.Index(fields=['department', 'is_active'], name='hr_departme_departm_390848_idx'),
        ),
    ]
