# Generated by Django 6.0.4 on 2026-06-17 10:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0079_backfill_designation_from_job_title'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationSalaryStructure',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('medical', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hourly overtime rate applied when shift policy allows OT.', max_digits=10)),
                ('late_penalty_per_minute', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late penalty rate per minute when late policy is enabled.', max_digits=10)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryAssignment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='designation',
            new_name='hr_designat_hospita_6a7577_idx',
            old_name='hr_designat_hospita_idx',
        ),
        migrations.AlterField(
            model_name='designation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='designation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='designationsalarystructure',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_structures', to='hr.designation'),
        ),
        migrations.AddField(
            model_name='designationsalarystructure',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designation_salary_structures', to='shared.hospital'),
        ),
        migrations.AddField(
            model_name='employeesalaryassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_assignments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeesalaryassignment',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_salary_assignments', to='hr.designationsalarystructure'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='employee_salary_assignment',
            field=models.ForeignKey(blank=True, help_text='Designation assignment used for this payroll run (audit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='hr.employeesalaryassignment'),
        ),
        migrations.AddIndex(
            model_name='designationsalarystructure',
            index=models.Index(fields=['hospital', 'designation', 'is_active'], name='hr_designat_hospita_516c19_idx'),
        ),
        migrations.AddIndex(
            model_name='designationsalarystructure',
            index=models.Index(fields=['designation', 'effective_from'], name='hr_designat_designa_ce305c_idx'),
        ),
        migrations.AddConstraint(
            model_name='designationsalarystructure',
            constraint=models.UniqueConstraint(fields=('hospital', 'designation', 'name'), name='unique_designation_salary_structure_name'),
        ),
        migrations.AddIndex(
            model_name='employeesalaryassignment',
            index=models.Index(fields=['employee', 'effective_from'], name='hr_employee_employe_ff3d09_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalaryassignment',
            index=models.Index(fields=['employee', 'is_active'], name='hr_employee_employe_3b465a_idx'),
        ),
    ]
