# Generated by Django 6.0.4 on 2026-06-17 10:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0081_migrate_to_designation_salary'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMonthFinalization',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(db_index=True, help_text='Payroll period in YYYY-MM format.', max_length=7)),
                ('finalized_at', models.DateTimeField()),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-month', '-finalized_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='finalized',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, row is frozen for payroll and attendance recalculation.'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_daily_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('PUBLISHED', 'Published'), ('FINALIZED', 'Finalized (legacy)')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['finalized', 'date'], name='hr_dailyatt_finaliz_b3d475_idx'),
        ),
        migrations.AddField(
            model_name='attendancemonthfinalization',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_months_finalized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancemonthfinalization',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_month_finalizations', to='shared.hospital'),
        ),
        migrations.AddIndex(
            model_name='attendancemonthfinalization',
            index=models.Index(fields=['hospital', 'month'], name='hr_attendan_hospita_01c5d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancemonthfinalization',
            constraint=models.UniqueConstraint(fields=('hospital', 'month'), name='unique_attendance_month_finalization'),
        ),
    ]
