# Generated by Django 6.0.6 on 2026-06-28 08:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0087_offerbuilderv2_offer_expiry_date'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, help_text='Device serial number (SN) from ADMS query params.', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=50)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_time_sync', models.DateTimeField(blank=True, null=True)),
                ('last_time_sync_status', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('userinfo_sync_requested', models.BooleanField(default=False, help_text='Whether DATA QUERY USERINFO was queued on last handshake.')),
            ],
            options={
                'ordering': ['name', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='BiometricDeviceCommand',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.PositiveIntegerField(help_text='ADMS command id (C:<id>:...).')),
                ('command_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acked', 'Acked'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('return_code', models.CharField(blank=True, default='', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricEnrollment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finger_id', models.PositiveSmallIntegerField()),
                ('is_enrolled', models.BooleanField(default=False)),
                ('template_size', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiometricRejectedPunch',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin', models.CharField(db_index=True, max_length=20)),
                ('punch_time', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(db_index=True, max_length=80)),
                ('raw_line', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-punch_time'],
            },
        ),
        migrations.CreateModel(
            name='BiometricSyncLog',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricUnlinkedUser',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('card_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('linked', 'Linked'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_attendance_enabled',
            field=models.BooleanField(default=False, help_text='When true and employee is active/onboarded, punches are accepted and user is pushed to devices.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_card_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_device_privilege',
            field=models.PositiveSmallIntegerField(default=0, help_text='ZKTeco Pri: 0=User, 1=Enroller, 2=Manager, 14=Admin'),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_pin',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Numeric device PIN; auto-assigned on first biometric sync.', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_sync_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('removed', 'Removed')], default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('biometric_pin__gt', '')), fields=('hospital', 'biometric_pin'), name='unique_biometric_pin_per_hospital'),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Assign after first handshake so punches map to the correct tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_devices', to='shared.hospital'),
        ),
        migrations.AddField(
            model_name='biometricdevicecommand',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='hr.biometricdevice'),
        ),
        migrations.AddField(
            model_name='biometricenrollment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='hr.biometricdevice'),
        ),
        migrations.AddField(
            model_name='biometricenrollment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_enrollments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='biometricrejectedpunch',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_punches', to='hr.biometricdevice'),
        ),
        migrations.AddField(
            model_name='biometricrejectedpunch',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_rejected_punches', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='biometricrejectedpunch',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_rejected_punches', to='shared.hospital'),
        ),
        migrations.AddField(
            model_name='biometricsynclog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='hr.biometricdevice'),
        ),
        migrations.AddField(
            model_name='biometricsynclog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_sync_logs', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='biometricsynclog',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_sync_logs', to='shared.hospital'),
        ),
        migrations.AddField(
            model_name='biometricunlinkeduser',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlinked_users', to='hr.biometricdevice'),
        ),
        migrations.AddField(
            model_name='biometricunlinkeduser',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_unlinked_users', to='shared.hospital'),
        ),
        migrations.AddField(
            model_name='biometricunlinkeduser',
            name='linked_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_biometric_unlinked_users', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='biometricunlinkeduser',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_biometric_unlinked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='biometricdevice',
            index=models.Index(fields=['hospital', 'is_active'], name='hr_biometri_hospita_eab2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdevicecommand',
            index=models.Index(fields=['device', 'status', 'created_at'], name='hr_biometri_device__fcd100_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometricdevicecommand',
            constraint=models.UniqueConstraint(fields=('device', 'command_id'), name='unique_biometric_device_command_id'),
        ),
        migrations.AddIndex(
            model_name='biometricenrollment',
            index=models.Index(fields=['employee', 'is_enrolled'], name='hr_biometri_employe_d1f318_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometricenrollment',
            constraint=models.UniqueConstraint(fields=('employee', 'device', 'finger_id'), name='unique_biometric_enrollment_per_finger'),
        ),
        migrations.AddIndex(
            model_name='biometricrejectedpunch',
            index=models.Index(fields=['pin', 'punch_time'], name='hr_biometri_pin_1f6a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricsynclog',
            index=models.Index(fields=['action', 'level', 'created_at'], name='hr_biometri_action_a6c819_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricunlinkeduser',
            index=models.Index(fields=['hospital', 'status'], name='hr_biometri_hospita_e03b8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometricunlinkeduser',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('hospital', 'pin'), name='unique_pending_unlinked_pin_per_hospital'),
        ),
    ]
