# Generated by Cursor on 2026-07-04

import re
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


COMPLIANCE_FIELDS = (
    'late_policy_enabled',
    'grace_minutes',
    'late_penalty_threshold_minutes',
    'late_penalty_type',
    'late_penalty_value',
    'late_conversion_enabled',
    'late_count_for_half_day',
    'late_count_for_full_day',
    'warning_after_n_lates',
    'half_day_after_n_lates',
    'full_day_after_n_lates',
    'overtime_enabled',
    'overtime_type',
    'weekend_ot_multiplier',
    'holiday_ot_multiplier',
)


def _base_code(*parts):
    text = ' '.join(str(part or '').strip() for part in parts if str(part or '').strip())
    cleaned = re.sub(r'[^A-Z0-9]+', '_', text.upper()).strip('_')
    return cleaned[:42] or 'LEVEL'


def _unique_code(existing_codes: set[str], base_code: str) -> str:
    candidate = base_code[:50] or 'LEVEL'
    if candidate not in existing_codes:
        existing_codes.add(candidate)
        return candidate

    counter = 2
    while counter < 1000:
        suffix = f'_{counter}'
        prefix = (base_code[: max(1, 50 - len(suffix))] or 'LEVEL').rstrip('_')
        candidate = f'{prefix}{suffix}'
        if candidate not in existing_codes:
            existing_codes.add(candidate)
            return candidate
        counter += 1
    raise RuntimeError('Could not generate a unique compensation level code during migration.')


def backfill_compensation_levels(apps, schema_editor):
    DesignationSalaryStructure = apps.get_model('hr', 'DesignationSalaryStructure')
    EmployeeSalaryAssignment = apps.get_model('hr', 'EmployeeSalaryAssignment')
    CompensationLevel = apps.get_model('hr', 'CompensationLevel')
    EmployeeCompensationAssignment = apps.get_model('hr', 'EmployeeCompensationAssignment')

    existing_codes_by_hospital = {}
    template_to_level_id = {}

    def ensure_level_from_template(template):
        cached = template_to_level_id.get(template.pk)
        if cached:
            return cached

        hospital_codes = existing_codes_by_hospital.setdefault(template.hospital_id, set())
        base_code = _base_code(
            getattr(template.designation, 'code', ''),
            getattr(template, 'name', ''),
            getattr(template.designation, 'name', ''),
        )
        code = _unique_code(hospital_codes, base_code)
        field_payload = {field: getattr(template, field) for field in COMPLIANCE_FIELDS}
        level = CompensationLevel.objects.create(
            created_at=template.created_at,
            updated_at=template.updated_at,
            hospital_id=template.hospital_id,
            designation_id=template.designation_id,
            code=code,
            name=template.name or getattr(template.designation, 'name', '') or code,
            rank=getattr(template.designation, 'level', 0) or 0,
            basic=template.basic,
            hra=template.hra,
            medical=template.medical,
            special_allowance=template.special_allowance,
            allowances={},
            deductions={},
            overtime_rate=template.overtime_rate,
            effective_from=template.effective_from,
            effective_to=template.effective_to,
            is_active=template.is_active,
            is_default_for_designation=bool(template.is_active),
            notes=f'Backfilled from designation salary structure {template.pk}.',
            **field_payload,
        )
        template_to_level_id[template.pk] = level.pk
        return level.pk

    active_templates = (
        DesignationSalaryStructure.objects.select_related('designation')
        .filter(is_active=True)
        .order_by('hospital_id', 'designation_id', 'effective_from', 'created_at')
    )
    for template in active_templates:
        ensure_level_from_template(template)

    active_assignments = (
        EmployeeSalaryAssignment.objects.select_related('salary_structure', 'salary_structure__designation')
        .filter(is_active=True)
        .order_by('employee_id', 'effective_from', 'created_at')
    )
    for assignment in active_assignments:
        template = assignment.salary_structure
        if template is None:
            continue
        level_id = ensure_level_from_template(template)
        EmployeeCompensationAssignment.objects.create(
            created_at=assignment.created_at,
            updated_at=assignment.updated_at,
            employee_id=assignment.employee_id,
            compensation_level_id=level_id,
            effective_from=assignment.effective_from,
            effective_to=assignment.effective_to,
            is_active=assignment.is_active,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0094_employee_archive_history'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationLevel',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('late_policy_enabled', models.BooleanField(default=False, help_text='When enabled, late penalty uses structure fields instead of global payroll settings.')),
                ('grace_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Grace minutes before late applies; defaults to employee shift when empty.', null=True)),
                ('late_penalty_threshold_minutes', models.PositiveSmallIntegerField(default=15, help_text='Minutes above grace before per-minute penalty billing starts.')),
                ('late_penalty_type', models.CharField(choices=[('per_minute', 'Per minute'), ('fixed_per_late_day', 'Fixed per late day'), ('percentage_daily_salary', 'Percentage of daily salary')], default='per_minute', max_length=32)),
                ('late_penalty_value', models.DecimalField(decimal_places=2, default=0, help_text='Rate per minute, fixed amount per late day, or percentage of daily salary.', max_digits=10)),
                ('late_conversion_enabled', models.BooleanField(default=False, help_text='Convert monthly late count into equivalent leave-day deductions.')),
                ('late_count_for_half_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('late_count_for_full_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('warning_after_n_lates', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('half_day_after_n_lates', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('full_day_after_n_lates', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overtime_enabled', models.BooleanField(default=True)),
                ('overtime_type', models.CharField(choices=[('fixed_per_hour', 'Fixed per hour'), ('percentage_hourly_rate', 'Percentage of hourly rate')], default='fixed_per_hour', max_length=32)),
                ('weekend_ot_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('holiday_ot_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.JSONField(blank=True, default=dict, help_text='Flexible allowance breakdown, e.g. {"transport": 1500, "meal": 800}.')),
                ('deductions', models.JSONField(blank=True, default=dict, help_text='Fixed monthly deductions, e.g. {"pf": 1800, "tax": 200}.')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, help_text='Hourly overtime rate applied when shift policy allows OT.', max_digits=10)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default_for_designation', models.BooleanField(db_index=True, default=False, help_text='Auto-assign this level to new employees for the linked designation.')),
                ('notes', models.TextField(blank=True, default='')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensation_levels', to='hr.designation')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_levels', to='shared.hospital')),
            ],
            options={
                'ordering': ['designation__name', 'rank', '-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensationAssignment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('compensation_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_compensation_assignments', to='hr.compensationlevel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_assignments', to='hr.employee')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompensationOverride',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('medical', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('allowances', models.JSONField(blank=True, default=None, help_text='Only supplied keys override inherited allowances.', null=True)),
                ('deductions', models.JSONField(blank=True, default=None, help_text='Only supplied keys override inherited deductions.', null=True)),
                ('overtime_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_compensation_overrides', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_overrides', to='hr.employee')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='compensationlevel',
            constraint=models.UniqueConstraint(fields=('hospital', 'code', 'effective_from'), name='unique_compensation_level_code_from_date'),
        ),
        migrations.AddIndex(
            model_name='compensationlevel',
            index=models.Index(fields=['hospital', 'designation', 'is_active'], name='hr_compensa_hospita_d65ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationlevel',
            index=models.Index(fields=['hospital', 'code', 'is_active'], name='hr_compensa_hospita_5c94ec_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationlevel',
            index=models.Index(fields=['designation', 'rank', 'effective_from'], name='hr_compensa_designa_a8bc73_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationlevel',
            index=models.Index(fields=['hospital', 'is_default_for_designation'], name='hr_compensa_hospita_048d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationassignment',
            index=models.Index(fields=['employee', 'effective_from'], name='hr_employeec_employe_c449d6_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationassignment',
            index=models.Index(fields=['employee', 'is_active'], name='hr_employeec_employe_9300c8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationoverride',
            index=models.Index(fields=['employee', 'effective_from'], name='hr_employeec_employe_97167d_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationoverride',
            index=models.Index(fields=['employee', 'is_active'], name='hr_employeec_employe_48aa16_idx'),
        ),
        migrations.RunPython(backfill_compensation_levels, migrations.RunPython.noop),
    ]
