# Generated by Django 6.0.4 on 2026-07-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0091_employee_exit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometricdevice',
            options={'ordering': ['name', 'serial_number'], 'verbose_name': 'Biometric Device', 'verbose_name_plural': 'Biometric Device Connections'},
        ),
    ]
