# Generated by Cursor on 2026-07-04

import re

import django.db.models.deletion
from django.db import migrations, models


COMPLIANCE_FIELDS = (
    'late_policy_enabled',
    'grace_minutes',
    'late_penalty_threshold_minutes',
    'late_penalty_type',
    'late_penalty_value',
    'late_conversion_enabled',
    'late_count_for_half_day',
    'late_count_for_full_day',
    'warning_after_n_lates',
    'half_day_after_n_lates',
    'full_day_after_n_lates',
    'overtime_enabled',
    'overtime_type',
    'weekend_ot_multiplier',
    'holiday_ot_multiplier',
)


def _base_code(*parts):
    text = ' '.join(str(part or '').strip() for part in parts if str(part or '').strip())
    cleaned = re.sub(r'[^A-Z0-9]+', '_', text.upper()).strip('_')
    return cleaned[:42] or 'LEVEL'


def _unique_code(existing_codes: set[str], base_code: str) -> str:
    candidate = base_code[:50] or 'LEVEL'
    if candidate not in existing_codes:
        existing_codes.add(candidate)
        return candidate

    counter = 2
    while counter < 1000:
        suffix = f'_{counter}'
        prefix = (base_code[: max(1, 50 - len(suffix))] or 'LEVEL').rstrip('_')
        candidate = f'{prefix}{suffix}'
        if candidate not in existing_codes:
            existing_codes.add(candidate)
            return candidate
        counter += 1
    raise RuntimeError('Could not generate a unique compensation level code during migration.')


def backfill_historical_compensation_assignments(apps, schema_editor):
    DesignationSalaryStructure = apps.get_model('hr', 'DesignationSalaryStructure')
    EmployeeSalaryAssignment = apps.get_model('hr', 'EmployeeSalaryAssignment')
    CompensationLevel = apps.get_model('hr', 'CompensationLevel')
    EmployeeCompensationAssignment = apps.get_model('hr', 'EmployeeCompensationAssignment')
    PayrollRun = apps.get_model('hr', 'PayrollRun')

    existing_codes_by_hospital = {}
    template_to_level_id = {}

    for row in CompensationLevel.objects.all().only('hospital_id', 'code'):
        existing_codes_by_hospital.setdefault(row.hospital_id, set()).add(row.code)

    def ensure_level_from_template(template):
        cached = template_to_level_id.get(template.pk)
        if cached:
            return cached

        note = f'Backfilled from designation salary structure {template.pk}.'
        existing = CompensationLevel.objects.filter(notes=note).only('pk').first()
        if existing:
            template_to_level_id[template.pk] = existing.pk
            return existing.pk

        codes = existing_codes_by_hospital.setdefault(template.hospital_id, set())
        base_code = _base_code(
            getattr(template.designation, 'code', ''),
            getattr(template, 'name', ''),
            getattr(template.designation, 'name', ''),
            str(template.pk).split('-')[0],
        )
        code = _unique_code(codes, base_code)
        field_payload = {field: getattr(template, field) for field in COMPLIANCE_FIELDS}
        level = CompensationLevel.objects.create(
            created_at=template.created_at,
            updated_at=template.updated_at,
            hospital_id=template.hospital_id,
            designation_id=template.designation_id,
            code=code,
            name=template.name or getattr(template.designation, 'name', '') or code,
            rank=getattr(template.designation, 'level', 0) or 0,
            basic=template.basic,
            hra=template.hra,
            medical=template.medical,
            special_allowance=template.special_allowance,
            allowances={},
            deductions={},
            overtime_rate=template.overtime_rate,
            effective_from=template.effective_from,
            effective_to=template.effective_to,
            is_active=template.is_active,
            is_default_for_designation=bool(template.is_active),
            notes=note,
            **field_payload,
        )
        template_to_level_id[template.pk] = level.pk
        return level.pk

    all_templates = (
        DesignationSalaryStructure.objects.select_related('designation')
        .order_by('hospital_id', 'designation_id', 'effective_from', 'created_at')
    )
    for template in all_templates:
        ensure_level_from_template(template)

    all_assignments = (
        EmployeeSalaryAssignment.objects.select_related('salary_structure', 'salary_structure__designation')
        .order_by('employee_id', 'effective_from', 'created_at')
    )
    legacy_to_comp_assignment = {}
    for assignment in all_assignments:
        template = assignment.salary_structure
        if template is None:
            continue
        existing = EmployeeCompensationAssignment.objects.filter(
            employee_id=assignment.employee_id,
            effective_from=assignment.effective_from,
        ).only('pk').first()
        if existing:
            legacy_to_comp_assignment[assignment.pk] = existing.pk
            continue

        level_id = ensure_level_from_template(template)
        created = EmployeeCompensationAssignment.objects.create(
            created_at=assignment.created_at,
            updated_at=assignment.updated_at,
            employee_id=assignment.employee_id,
            compensation_level_id=level_id,
            effective_from=assignment.effective_from,
            effective_to=assignment.effective_to,
            is_active=assignment.is_active,
        )
        legacy_to_comp_assignment[assignment.pk] = created.pk

    for payroll_run in PayrollRun.objects.exclude(employee_salary_assignment_id__isnull=True):
        comp_assignment_id = legacy_to_comp_assignment.get(payroll_run.employee_salary_assignment_id)
        if comp_assignment_id:
            payroll_run.employee_compensation_assignment_id = comp_assignment_id
            payroll_run.save(update_fields=['employee_compensation_assignment'])


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0089_compensation_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='employee_compensation_assignment',
            field=models.ForeignKey(
                blank=True,
                help_text='Compensation-level assignment used for this payroll run (audit).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='payroll_runs',
                to='hr.employeecompensationassignment',
            ),
        ),
        migrations.RunPython(backfill_historical_compensation_assignments, migrations.RunPython.noop),
    ]
