# Generated by Django 6.0.4 on 2026-07-15 06:17

import django.utils.timezone
import uuid
from django.db import migrations, models

from apps.hr.migration_ops import RenameIndexIdempotent


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0100_biometricrejectedpunch_dismissed'),
    ]

    operations = [
        RenameIndexIdempotent(
            model_name='compensationlevel',
            new_name='hr_compensa_hospita_014039_idx',
            old_name='hr_compensa_hospita_d65ee7_idx',
        ),
        RenameIndexIdempotent(
            model_name='compensationlevel',
            new_name='hr_compensa_hospita_131749_idx',
            old_name='hr_compensa_hospita_5c94ec_idx',
        ),
        RenameIndexIdempotent(
            model_name='compensationlevel',
            new_name='hr_compensa_designa_89f0a1_idx',
            old_name='hr_compensa_designa_a8bc73_idx',
        ),
        RenameIndexIdempotent(
            model_name='compensationlevel',
            new_name='hr_compensa_hospita_dc6a3d_idx',
            old_name='hr_compensa_hospita_048d4a_idx',
        ),
        RenameIndexIdempotent(
            model_name='employeecompensationassignment',
            new_name='hr_employee_employe_a5b8d0_idx',
            old_name='hr_employeec_employe_c449d6_idx',
        ),
        RenameIndexIdempotent(
            model_name='employeecompensationassignment',
            new_name='hr_employee_employe_e7830a_idx',
            old_name='hr_employeec_employe_9300c8_idx',
        ),
        RenameIndexIdempotent(
            model_name='employeecompensationoverride',
            new_name='hr_employee_employe_c58569_idx',
            old_name='hr_employeec_employe_97167d_idx',
        ),
        RenameIndexIdempotent(
            model_name='employeecompensationoverride',
            new_name='hr_employee_employe_9b73dd_idx',
            old_name='hr_employeec_employe_48aa16_idx',
        ),
        RenameIndexIdempotent(
            model_name='employeestatushistory',
            new_name='hr_employee_employe_d7c9d3_idx',
            old_name='hr_employe_employe_67e3d8_idx',
        ),
        RenameIndexIdempotent(
            model_name='employeestatushistory',
            new_name='hr_employee_employe_20e860_idx',
            old_name='hr_employe_employe_24d66c_idx',
        ),
        migrations.AlterField(
            model_name='employeestatushistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='employeestatushistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employeestatushistory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
