# Generated by Django 6.0.6 on 2026-07-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0098_rename_hr_compensa_hospita_d65ee7_idx_hr_compensa_hospita_014039_idx_and_more'),
        ('hr', '0101_rename_hr_compensa_hospita_d65ee7_idx_hr_compensa_hospita_014039_idx_and_more'),
    ]

    operations = [
    ]
