# Generated by Django 6.0.6 on 2026-07-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_management', '0020_receptionportalsettings_document_next_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionportalsettings',
            name='document_next_numbers',
        ),
    ]
