# Generated by Django 5.0.7 on 2026-09-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_management', '0023_clear_placeholder_hospital_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionportalsettings',
            name='time_display_mode',
            field=models.CharField(choices=[('12h', '12 hour'), ('24h', '24 hour')], default='12h', help_text='Hospital-wide time display: 12 hour or 24 hour.', max_length=4),
        ),
    ]
