# Generated by Django 5.0.7 on 2026-09-18 07:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0027_merge_20260616_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Paise adjustment folded into grand_total so retail bills settle in whole rupees.', max_digits=6),
        ),
    ]
