# Generated by Django 5.0.7 on 2026-07-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_hospitalcustomrxsalt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hospitalcustomrxsalt',
            new_name='doctors_hos_hospita_209b55_idx',
            old_name='doctors_hos_hospita_idx',
        ),
    ]
