# Generated by Django 5.0.7 on 2026-06-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expensetransaction_source'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expenseparty',
            new_name='expenses_ex_hospita_1cd89d_idx',
            old_name='expenses_ex_party_idx',
        ),
        migrations.RenameIndex(
            model_name='expensequickcategory',
            new_name='expenses_ex_hospita_e09613_idx',
            old_name='expenses_ex_hospita_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='expensequickcategory',
            new_name='expenses_ex_hospita_1f7be5_idx',
            old_name='expenses_ex_hospita_name_idx',
        ),
        migrations.RenameIndex(
            model_name='expensequickservice',
            new_name='expenses_ex_hospita_1f14eb_idx',
            old_name='expenses_ex_hospita_idx',
        ),
        migrations.RenameIndex(
            model_name='expensequickservice',
            new_name='expenses_ex_hospita_05b483_idx',
            old_name='expenses_ex_hospita_label_idx',
        ),
    ]
